# Generated by Django 4.2.30 on 2026-05-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('message', 'Message'), ('story_reaction', 'Story Reaction'), ('story_reply', 'Story Reply'), ('reel_like', 'Reel Like'), ('reel_comment', 'Reel Comment')], max_length=20),
        ),
    ]
