# Generated by Django 4.2.30 on 2026-06-19 11:16

import apps.reels.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0003_savedreel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(storage=apps.reels.storage.VideoCloudinaryStorage(), upload_to='reels/'),
        ),
    ]
