# Generated by Django 4.2.30 on 2026-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='song_artist',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='story',
            name='song_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='story',
            name='text_overlay',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
