# Generated by Django 4.2.30 on 2026-05-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_song_artist_story_song_name_story_text_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text_rotation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='text_size_idx',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='story',
            name='text_style_id',
            field=models.CharField(blank=True, default='classic', max_length=30),
        ),
        migrations.AddField(
            model_name='story',
            name='text_x',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='story',
            name='text_y',
            field=models.FloatField(default=50.0),
        ),
    ]
