# Generated by Django 4.2.30 on 2026-05-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_text_rotation_story_text_size_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='media_fit',
            field=models.CharField(default='contain', max_length=10),
        ),
        migrations.AddField(
            model_name='story',
            name='media_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='story',
            name='media_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='media_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='music_rotation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='music_x',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='story',
            name='music_y',
            field=models.FloatField(default=75.0),
        ),
    ]
