# Generated by Django 4.2.30 on 2026-05-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music_artist',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
        migrations.AddField(
            model_name='post',
            name='music_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
